server:
  port: ${PORT:8080}
  servlet:
    context-path: /api/manager

spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: register-part
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: ${SCHEMA_NAME}
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    open-in-view: false

file-manager:
  base-url: ${BASE_URL}
  upload: ${UPLOAD_URI}
  download: ${DOWNLOAD_URI}